### ISSUE TITLE
Si on change de bars via le sélecteur, les différents tooltips restent ouverts

### ISSUE THREAD

**Issue by Raphbub** [Raphbub/dataBinch#13]
Trouver un moyen de fermer les tooltips automatiquement ouverts

**Comment by Raphbub** [comment]
Plus de problème, mais gain d'efficacité si on arrive à travailler directement sur la bonne couche que sur toutes --> **Améliorer cette fonction**
```
map.eachLayer(function(l) {
   map.closeTooltip(l.getTooltip());
})
```

**Comment by ipante** [comment]
Félicitations pour toutes ces améliorations. Votre projet gagne chaque jour en clarté et en qualité!

**Comment by Raphbub** [comment]
Avec l'ouverture des tooltips de brasseries qui sont situés dans une autre couche, cette fonction devient pertinente
