### ISSUE TITLE
Restriction par type de bière

### ISSUE THREAD

**Issue by Raphbub** [Raphbub/dataBinch#26]
Laisser à l'utilisateur qui préférerait certains styles de bières la possibilité de n'afficher que ces styles pour marquer le coup là où ça pourra lui plaire

**Comment by rxlacroix** [comment]
Fait.
Un certain nombre de styles avec 1-2 bières, à voir si l'on attend/espère un remplissage de ces catégories par les nouveaux bars/villes qui vont arriver ou si l'on restreint sur des styles plus larges.
